<?php

class Forms{
    // Attribut
    private $username;


    // Getter and Setter
    /**
     * @return String
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param String $username
     */
    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function Forms($username)
    {
        $this->setUsername($username);
    }
    // Functions

    /**
     * @param String $name
     * @param bool|False $password
     * @return string
     */
    public function input($name, $password=False)
    {
        $formInput = '<div class="form-group">';
        $formInput .= '<label for="'.$name.'">'.$name.'</label>';
        $formInput .= '<input type="';
        if($password)
            $formInput .= 'password';
        else
            $formInput .= 'text';
        $formInput .= '" class="form-control" id="'.$name.'" name="'.$name.'" placeholder="'.$name.'">';
        $formInput .= '</div>';

        return $formInput;
    }

    /**
     * @param String $name
     * @return string
     */
    public function textarea($name)
    {
        $formTextarea = '<div class="form-group">';
        $formTextarea .= '<textarea name="'.$name.'" id="'.$name.'" class="form-control" rows="3"></textarea>';
        $formTextarea .= '</div>';
        return $formTextarea;

    }

    /**
     * @param $name
     * @param Array $elements
     * @param bool|False $multiple
     * @return string
     */
    public function select($name, $elements, $multiple=False)
    {
        if(is_array($elements)){
            $formselect = '<div class="form-group">';
            $formselect .= '<select';
            if($multiple)
                $formselect .= 'multiple';
            $formselect .=' id="'.$name.'" name="'.$name.'" class="form-control">';
            foreach($elements as $element){
                $formselect .= '<option>'.$element.'</option>';
            }
            $formselect .= '</select>';
            $formselect .= '</div>';
            return $formselect;
        }else{
            $error = '$elements is not an Array';
            return $error;
        }
        
    }

    /**
     * @param String $name
     * @return string
     */
    public function password($name)
    {
        $formPassword = $this->input($name, True);

        return $formPassword;
    }


    /**
     * @param String $name
     * @param Array $elements
     * @return string
     */
    public function bpRadio($name, $elements)
    {
        $i = 1;
        $formRadio = '<label class="radio-inline">';
        foreach($elements as $element){
            $formRadio .= '<label class="radio-inline">';
            $formRadio .= '<input type="radio" id="'.$name.$i.'" name="'.$name.$i.'" value="option1"> '.$element;
            $formRadio .= '</label>';
            $i++;
        }
        $formRadio .= '</label>';
        return $formRadio;
    }

    /**
     * @param String $name
     * @param Array $elements
     * @return string
     */
    public function checkbox($name, $elements)
    {
        $i = 1;
        $formCheckbox = '<label class="radio-inline">';
        foreach($elements as $element){
            $formCheckbox .= '<label class="checkbox-inline">';
            $formCheckbox .= '<input type="checkbox" id="'.$name.$i.'" name="'.$name.$i.'" value="option1">'.$element;
            $formCheckbox .= '</label>';
            $i++;
        }
        $formCheckbox .= '</label>';
        return $formCheckbox;
    }

    /**
     * @return string
     */
    public function initForm()
    {
        $base = 'Generated by '.$this->getUsername();
        $base .= '<form method="post" action="index.php">';
        return $base;
    }

    /**
     * @return string
     */
    public function endForm()
    {
        return '</form>';
    }

    public function buttons($name)
    {
        return '<button type="submit" d="'.$name.'" name="'.$name.'" class="btn btn-default">'.$name.'</button>';
    }
}